# ML Testing
Equipo 1 - Fase 1

Import Test dataset

In [3]:
import pandas as pd
df_test = pd.read_csv("https://raw.githubusercontent.com/Pakohp88/Equipo1_mlops/integration/data/v0.1.0/test.csv");
df_test.head()


Class  _RMSenergy_Mean  _Lowenergy_Mean  _Fluctuation_Mean  _Tempo_Mean  \
0  happy         0.136558        -0.481702           0.319799     0.203612   
1  angry         0.100353         0.730461          -0.749911    -0.122797   
2  angry         0.064079         0.730461          -0.355476    -1.440407   
3  happy        -1.134585        -0.455246          -0.915281    -0.660674   
4  relax        -1.095969         0.321481           0.422530     1.284223   

   _MFCC_Mean_1  _MFCC_Mean_2  _MFCC_Mean_3  _MFCC_Mean_4  _MFCC_Mean_5  ...  \
0     -0.716701     -1.495734     -0.109325      0.072996     -0.601010  ...   
1      0.632760      0.534660      0.623917      1.179529      0.861329  ...   
2      0.709150      0.467161      0.575217      0.918655      0.246050  ...   
3     -1.566860     -1.207301      0.473878     -2.639843     -0.187019  ...   
4      1.225830      2.097425      1.424792      1.637264      0.951978  ...   

   _Chromagram_Mean_9  _Chromagram_Mean_10  _Chromagram_Mean_11  \
0           -1.176407            -0.921285             0.216342   
1           -0.112205            -1.121371            -0.579270   
2           -0.674834             0.163618            -0.967648   
3            0.135092             0.743970             0.836209   
4           -1.566234            -1.681931            -1.567769   

   _Chromagram_Mean_12  _HarmonicChangeDetectionFunction_Mean  \
0            -0.597432                               1.160081   
1            -0.838474                               0.027797   
2            -1.335030                              -1.989278   
3             0.321505                              -0.310743   
4            -1.384964                              -0.536640   

   _HarmonicChangeDetectionFunction_Std  \
0                              0.717326   
1                             -1.712832   
2                             -1.560178   
3                             -0.913008   
4                              0.956330   

   _HarmonicChangeDetectionFunction_Slope  \
0                               -2.066091   
1                               -0.288834   
2                                0.977716   
3                                1.149426   
4                               -0.723654   

   _HarmonicChangeDetectionFunction_PeriodFreq  \
0                                     0.555334   
1                                     1.049265   
2                                    -0.512529   
3                                    -1.100173   
4                                     0.186686   

   _HarmonicChangeDetectionFunction_PeriodAmp  \
0                                    0.354669   
1                                    2.594664   
2                                   -0.342432   
3                                    0.423890   
4                                   -1.827898   

   _HarmonicChangeDetectionFunction_PeriodEntropy  
0                                       -1.428702  
1                                       -0.041494  
2                                       -2.043121  
3                                       -0.041494  
4                                        2.036344  

[5 rows x 51 columns]

Import Train dataset

In [4]:
df_train = pd.read_csv("https://raw.githubusercontent.com/Pakohp88/Equipo1_mlops/integration/data/v0.1.0/train.csv");
df_train.head()

Class  _RMSenergy_Mean  _Lowenergy_Mean  _Fluctuation_Mean  _Tempo_Mean  \
0  happy        -0.619718         0.566276           0.575214     0.255794   
1  happy        -0.600912         1.563262          -0.217664    -0.717500   
2  happy        -0.657386         0.051567           0.402023     0.191051   
3    sad         1.277284        -0.428768          -0.749008    -1.856073   
4  relax         1.681760        -0.028981           0.191826    -0.531055   

   _MFCC_Mean_1  _MFCC_Mean_2  _MFCC_Mean_3  _MFCC_Mean_4  _MFCC_Mean_5  ...  \
0     -1.477189     -1.048422      0.552719     -1.402778      1.181805  ...   
1     -1.576094     -0.071492     -0.308368      1.164707      0.252072  ...   
2      0.006936     -0.425733     -1.290155     -1.533158     -0.235071  ...   
3      0.874310      0.107062      0.183410      0.558031     -0.930237  ...   
4      1.134898      1.013364     -0.500834      0.011195      1.417949  ...   

   _Chromagram_Mean_9  _Chromagram_Mean_10  _Chromagram_Mean_11  \
0            1.605940             0.481179            -0.774464   
1           -0.711313             1.117071            -1.022109   
2           -0.258527             1.113237             0.849253   
3           -0.769747             0.537042            -0.310133   
4            1.517967             0.150507             1.664920   

   _Chromagram_Mean_12  _HarmonicChangeDetectionFunction_Mean  \
0            -0.671563                              -0.074084   
1             0.199431                              -0.213466   
2             0.941168                               0.916354   
3            -1.069593                               0.940322   
4             1.438951                               0.635600   

   _HarmonicChangeDetectionFunction_Std  \
0                             -0.116987   
1                             -0.357425   
2                             -0.276637   
3                              1.393941   
4                              0.932705   

   _HarmonicChangeDetectionFunction_Slope  \
0                                1.018159   
1                                1.048474   
2                               -1.486166   
3                               -0.381764   
4                               -0.423110   

   _HarmonicChangeDetectionFunction_PeriodFreq  \
0                                     0.555334   
1                                     1.049265   
2                                     0.555334   
3                                     0.555334   
4                                     0.555334   

   _HarmonicChangeDetectionFunction_PeriodAmp  \
0                                    0.066304   
1                                    0.470609   
2                                    0.711226   
3                                   -1.303932   
4                                   -0.849714   

   _HarmonicChangeDetectionFunction_PeriodEntropy  
0                                        0.740115  
1                                        2.036344  
2                                       -0.409430  
3                                       -0.041494  
4                                        0.341485  

[5 rows x 51 columns]

Import validation dataset

In [5]:
df_validation = pd.read_csv("https://raw.githubusercontent.com/Pakohp88/Equipo1_mlops/integration/data/v0.1.0/val.csv");
df_validation.head()

Class  _RMSenergy_Mean  _Lowenergy_Mean  _Fluctuation_Mean  _Tempo_Mean  \
0  angry        -0.714026         0.321481          -0.442824     2.012988   
1  happy        -1.407094        -0.349203           0.163569    -0.022889   
2  happy         0.776769         0.620917           1.106410    -0.556990   
3  happy         1.446864         0.402882           1.008737    -0.662407   
4  angry         1.665078        -1.239459          -1.226815    -0.697051   

   _MFCC_Mean_1  _MFCC_Mean_2  _MFCC_Mean_3  _MFCC_Mean_4  _MFCC_Mean_5  ...  \
0     -2.484709      0.171471      0.851650      0.582261      0.619805  ...   
1     -0.652048     -1.135160     -0.273838     -0.635720      0.408721  ...   
2      0.015133     -0.543236     -0.296854      0.737806      0.607736  ...   
3     -0.373291      0.016894     -0.702170      0.001700     -1.157287  ...   
4     -0.137291      0.991466      1.273929      0.640495      0.300257  ...   

   _Chromagram_Mean_9  _Chromagram_Mean_10  _Chromagram_Mean_11  \
0            0.163533             1.117071             0.051675   
1           -1.163882            -0.539986             1.501603   
2            0.921108             1.117071             1.244282   
3            0.201975             0.266340             1.702967   
4           -0.275893            -0.931359             0.484087   

   _Chromagram_Mean_12  _HarmonicChangeDetectionFunction_Mean  \
0            -0.521471                              -0.406152   
1             0.984205                               1.648637   
2            -0.099183                               0.821369   
3             0.645004                               0.301981   
4             1.170698                               0.194916   

   _HarmonicChangeDetectionFunction_Std  \
0                              0.765621   
1                              1.003399   
2                             -0.438866   
3                             -0.357425   
4                             -0.603728   

   _HarmonicChangeDetectionFunction_Slope  \
0                                0.214713   
1                               -1.823024   
2                               -0.381764   
3                               -1.570235   
4                                1.058576   

   _HarmonicChangeDetectionFunction_PeriodFreq  \
0                                    -1.779323   
1                                     0.186686   
2                                    -0.098224   
3                                    -1.100173   
4                                     0.555334   

   _HarmonicChangeDetectionFunction_PeriodAmp  \
0                                   -1.124176   
1                                   -0.143174   
2                                    1.394703   
3                                    0.963921   
4                                    1.366789   

   _HarmonicChangeDetectionFunction_PeriodEntropy  
0                                        0.740115  
1                                       -0.041494  
2                                       -0.041494  
3                                        0.341485  
4                                       -0.041494  

[5 rows x 51 columns]

## ML model evaluation
Construir, ajustar y evaluar modelos de Machine Learning utilizando técnicas y algoritmos apropiados al problema.

Instrucciones:

1. Seleccionar 5 algoritmos de Machine Learning adecuados para resolver el problema planteado
2. Realizar ajustes de hiperparámetros para optimizar el rendimiento del modelo.
3. Evaluar los modelos utilizando la métrica de accuracy.






## Preparacion de los datos para modelado

Separamos las variables de características (X) y la variable objetivo (y) para los conjuntos de datos de entrenamiento, prueba y validación


In [6]:
X_train = df_train.drop('Class', axis=1)
y_train = df_train['Class']

X_test = df_test.drop('Class', axis=1)
y_test = df_test['Class']

X_validation = df_validation.drop('Class', axis=1)
y_validation = df_validation['Class']

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)
print("X_validation shape:", X_validation.shape)
print("y_validation shape:", y_validation.shape)

X_train shape: (91, 50)
y_train shape: (91,)
X_test shape: (31, 50)
y_test shape: (31,)
X_validation shape: (30, 50)
y_validation shape: (30,)


## Seleccionar y entrenar modelos

Eligimos 5 algoritmos de clasificación apropiados y entrenamos cada modelo utilizando los datos de entrenamiento.


In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# Instantiate each model with default parameters
log_reg = LogisticRegression()
dec_tree = DecisionTreeClassifier()
rand_forest = RandomForestClassifier()
svm_model = SVC()
knn_model = KNeighborsClassifier()
gradient_boosting = GradientBoostingClassifier()


# Train each model
log_reg.fit(X_train, y_train)
dec_tree.fit(X_train, y_train)
rand_forest.fit(X_train, y_train)
svm_model.fit(X_train, y_train)
knn_model.fit(X_train, y_train)
gradient_boosting.fit(X_train, y_train)

print("Models trained successfully.")

Models trained successfully.


## Ajustar hiperparámetros
Optimizar el rendimiento de cada modelo ajustando sus hiperparámetros.


In [8]:
from sklearn.model_selection import GridSearchCV

# Define parameter grids
param_grid_log_reg = {
    'C': [0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs']
}

param_grid_dec_tree = {
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

param_grid_rand_forest = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

param_grid_svm = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf']
}

param_grid_knn = {
    'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance']
}

param_grid_gradient_boosting = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7]
}

Aplicacion de GridSearchCV para cada modelo para encontrar los mejores hiperparametros.



In [9]:
# Perform GridSearchCV for each model
grid_search_log_reg = GridSearchCV(log_reg, param_grid_log_reg, cv=5)
grid_search_dec_tree = GridSearchCV(dec_tree, param_grid_dec_tree, cv=5)
grid_search_rand_forest = GridSearchCV(rand_forest, param_grid_rand_forest, cv=5)
grid_search_svm = GridSearchCV(svm_model, param_grid_svm, cv=5)
grid_search_knn = GridSearchCV(knn_model, param_grid_knn, cv=5)
grid_search_gradient_boosting = GridSearchCV(gradient_boosting, param_grid_gradient_boosting, cv=5)

# Fit GridSearchCV to the training data
grid_search_log_reg.fit(X_train, y_train)
grid_search_dec_tree.fit(X_train, y_train)
grid_search_rand_forest.fit(X_train, y_train)
grid_search_svm.fit(X_train, y_train)
grid_search_knn.fit(X_train, y_train)
grid_search_gradient_boosting.fit(X_train, y_train)

# Store the best estimators
best_log_reg = grid_search_log_reg.best_estimator_
best_dec_tree = grid_search_dec_tree.best_estimator_
best_rand_forest = grid_search_rand_forest.best_estimator_
best_svm = grid_search_svm.best_estimator_
best_knn = grid_search_knn.best_estimator_
best_gradient_boosting = grid_search_gradient_boosting.best_estimator_

print("Hyperparameter tuning completed and best estimators stored.")

Hyperparameter tuning completed and best estimators stored.


## Evaluar modelos
Evaluamos cada modelo entrenado y ajustado utilizando los conjuntos de validación y prueba, reportando la puntuación de precisión (accuracy) de cada uno.


In [10]:
from sklearn.metrics import accuracy_score
import pandas as pd

models = {
    "Logistic Regression": best_log_reg,
    "Decision Tree": best_dec_tree,
    "Random Forest": best_rand_forest,
    "SVM": best_svm,
    "KNN": best_knn,
    "Gradient Boosting": best_gradient_boosting
}

for model_name, model in models.items():
    # Evaluate on validation set
    y_validation_pred = model.predict(X_validation)
    accuracy_validation = accuracy_score(y_validation, y_validation_pred)
    # print(f"{model_name} Accuracy (Validation Set): {accuracy_validation:.4f}")

    # Evaluate on test set
    y_test_pred = model.predict(X_test)
    accuracy_test = accuracy_score(y_test, y_test_pred)
    # print(f"{model_name} Accuracy (Test Set): {accuracy_test:.4f}")


# Create a dictionary to store the results
results_data = {
    "Model": ["Logistic Regression", "Decision Tree", "Random Forest", "SVM", "KNN", "Gradient Boosting"],
    "Validation Accuracy": [0.6333, 0.6000, 0.6667, 0.6667, 0.5667, 0.5667],
    "Test Accuracy": [0.8065, 0.6774, 0.8387, 0.8065, 0.6452, 0.6452]
}

# Create the DataFrame
evaluation_results_df = pd.DataFrame(results_data)

# Display the DataFrame
display(evaluation_results_df)

Model  Validation Accuracy  Test Accuracy
0  Logistic Regression               0.6333         0.8065
1        Decision Tree               0.6000         0.6774
2        Random Forest               0.6667         0.8387
3                  SVM               0.6667         0.8065
4                  KNN               0.5667         0.6452
5    Gradient Boosting               0.5667         0.6452

## Resumen:
### Hallazgos clave del análisis de datos

* Se seleccionaron y entrenaron seis algoritmos de
clasificación: Regresión Logística, Árbol de Decisión, Bosque Aleatorio (Random Forest), Máquina de Vectores de Soporte (SVM), Vecinos más Cercanos (KNN) y Gradient Boosting.

* Se realizó el ajuste de hiperparámetros utilizando GridSearchCV con validación cruzada de 5 particiones (folds) para cada modelo.

* El modelo de Bosque Aleatorio obtuvo la mayor precisión tanto en el conjunto de validación (0.6667) como en el conjunto de prueba (0.8387).

* El modelo SVM también mostró un buen desempeño, con una precisión de validación de 0.6667 y una precisión de prueba de 0.8065.

* La Regresión Logística mostró un aumento notable en la precisión desde el conjunto de validación (0.6333) hasta el conjunto de prueba (0.8065).

* Los modelos Árbol de Decisión, KNN y Gradient Boosting presentaron puntuaciones de precisión generalmente más bajas en comparación con los otros modelos.

### Conclusiones o próximos pasos

* Dado su rendimiento superior en los conjuntos de validación y prueba, el modelo de Bosque Aleatorio parece ser el más prometedor para esta tarea de clasificación.

* Un análisis adicional podría incluir la exploración de otras métricas de evaluación (por ejemplo, precisión, recall, F1-score) para obtener una comprensión más completa del rendimiento del modelo, especialmente si el conjunto de datos está desbalanceado.
